name: Deploy Site to AWS

on:
    push:
        branches: [main]
        
permissions:
    id-token: write
    contents: read

jobs:
    Upload-To-S3:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4.1.7
            
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4.0.2
              with:
                  aws-region: us-west-1
                  role-to-assume: arn:aws:iam::533267264662:role/PersonalSiteGithubActionsRole
                  
            - name: Upload to S3
              run: aws s3 cp . s3://gavinmccabe-personal-site/ --recursive --exclude ".*" --exclude "*/.*"

    Create-Cloudfront-Invalidation:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4.1.7

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4.0.2
              with:
                  aws-region: us-west-1
                  role-to-assume: arn:aws:iam::533267264662:role/PersonalSiteGithubActionsRole

            - name: Get Changed Files
              id: changed-files
              uses: tj-actions/changed-files@v44.5.6
              with:
                files: |
                  index.html
                  resume.yaml
                  script.js
                  styles.css

            - name: Invalidate Cloudfront Cache
              env:
                ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
              run: |
                for file in ${ALL_CHANGED_FILES}; do
                    echo "Invalidating cache for ${file}"
                    aws cloudfront create-invalidation --distribution-id EMISZ7YVLTJ6P --paths ${file}
                done
